### ISSUE TITLE
[Bug Report] 统计似乎不准

### ISSUE THREAD

**Issue by jason-huang03** [leverimmy/THU-Annual-Eat#17]
统计量和我印象中的有较大出入，别的同学有遇到这种问题吗？

**Comment by leverimmy** [comment]
您好，请问有具体的数据（or 例子）吗？

**Comment by ReaperWLLLLL** [comment]
这个应该只有新卡的数据

**Comment by leverimmy** [comment]
> 这个应该只有新卡的数据

确实。

**Comment by jason-huang03** [comment]
噢这样，那可能是对的。

**Comment by Ther-nullptr** [comment]
我看了下，感觉是收银机信息没同步，导致记录菜品和实际菜品有问题
比如清芬的麻辣烫算成了川渝小吃，桃李的烧鸟算成了擂椒拌饭，听涛的猪脚饭和打抛猪算成了麻辣香锅
