### ISSUE TITLE
[Bug Report] 写入文件路径应为config.json

### ISSUE THREAD

**Issue by ShallowDream0745** [leverimmy/THU-Annual-Eat#2]
41行写入json的时候应为config.json，而不是account.json
![图片](https://github.com/user-attachments/assets/342b32b9-7067-4450-9d31-4e5e5e421d0b)

**Comment by leverimmy** [comment]
谢谢！已在 [03bcb37](https://github.com/leverimmy/THU-Annual-Eat/commit/03bcb37fbe8510d8d8de4b786caaed4077643a18) 中修改。
