### ISSUE TITLE
[Bug Report] JSON Decode 报错

### ISSUE THREAD

**Issue by libercoinx** [leverimmy/THU-Annual-Eat#20]
![FC7D59209D32CBB93A40FF1D8E401D78](https://github.com/user-attachments/assets/d3ade444-8289-4843-992c-1a0aa8f2a57f)
报错JSONDecoderError，config.json如下图，应该没格式错误吧
<img width="207" alt="Snipaste_2024-12-21_16-45-34" src="https://github.com/user-attachments/assets/18ae36be-98b6-488e-8620-df5737a27ea1" />

**Comment by luckyzdz** [comment]
要复制servicehall后面的字符，那一串字母，你这个是serviceid

**Comment by libercoinx** [comment]
> 要复制servicehall后面的字符，那一串字母，你这个是serviceid

好的谢谢！！
