### ISSUE TITLE
[Bug Report] 网页的cookie路径似乎被修改了（附servicehall的新位置）

### ISSUE THREAD

**Issue by pk-1999** [leverimmy/THU-Annual-Eat#25]
华清大学校园卡综合服务网站网络传输请求servicehall的位置目前似乎更换到了`queryMessageNotifyList`中
![截屏2024-12-21 20 37 31](https://github.com/user-attachments/assets/61f118ac-f8b3-47c2-a803-5573d9cd0bdf)

**Comment by leverimmy** [comment]
在与学校储存数据的服务器后端的交互过程中，**所有的查询请求**的 Cookies 中都会包含 servicehall 字段。您给出了另一个地址，这并不意味着学校“更换了地址“。

**Comment by pk-1999** [comment]
嗷是这样，学到了（主要是我当时没找到`userselftrade`🥺
