### ISSUE TITLE
[Bug Report] 学校网站安全问题

### ISSUE THREAD

**Issue by ArtisticFantasy** [leverimmy/THU-Annual-Eat#27]
首先，感谢作者大大的贡献，但是其实这个项目也反映出了一个安全问题，id.tsinghua.edu.cn在检测到新设备时会采用2FA，而作者大大在实现的时候只要获得cookie哪怕直接通过request库发送不包含浏览器信息的post请求就能够直接访问服务，也就是说cookie可以直接绕过2FA，这也反映出只有id.tsinghua.edu.cn会对设备进行检验，而其余服务不会。我觉得这是一个安全问题，可能需要报送给信息办？并且后续最好改为基于浏览器内核的爬虫，比如基于selenium库实现，这样相对会更安全

**Comment by leverimmy** [comment]
我不认为这是一个安全问题，因为 cookies 中的 servicehall 等字段是会过期的。

**Comment by ArtisticFantasy** [comment]
这个过期设置有具体进行测量吗？是浏览器关闭时过期还是定时过期？如果是前者的话假设用户点击了另一个网页，且存在XSS漏洞被攻击者获取了学校网站cookie，然后攻击者通过自己的浏览器把cookie续上就危险了

**Comment by leverimmy** [comment]
应该是定时过期。

**Comment by leverimmy** [comment]
应该是 session 关闭时过期。这的确是一个很严重的问题。
