### ISSUE TITLE
[Code Refactor] 用户名和密码信息并没有用到

### ISSUE THREAD

**Issue by hotwords123** [leverimmy/THU-Annual-Eat#3]
如题，脚本需要输入 `username` 和 `password` 字段，但只是把它们保存到 JSON 了，发请求时没有用到。

**Comment by hotwords123** [comment]
以及，建议在 README 展示请求截图时把敏感的 cookie 信息打码一下（

**Comment by leverimmy** [comment]
> 如题，脚本需要输入 `username` 和 `password` 字段，但只是把它们保存到 JSON 了，发请求时没有用到。

已在 [5db51ff](https://github.com/leverimmy/THU-Annual-Eat/commit/5db51ff32278e66fd4eb83e607b9a258ccde3421) 修改。

**Comment by leverimmy** [comment]
> 以及，建议在 README 展示请求截图时把敏感的 cookie 信息打码一下（

感谢提醒！
